# docker compose --env-file ./.env.test  up
version: '1.0'
services:
### MySQL Container
  mysql:
    build:
      dockerfile: Dockerfile
      context: .
      # dockerfile: dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306